import { StyleSheet } from 'react-native';
import { Colors } from '../../common/Colors';
import { Fonts } from '../../common/Fonts';

export const styles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: '#F4F7F6',
    },
    planCard: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        marginHorizontal: 10,
        marginTop: 8,
        borderRadius: 16,
        padding: 12,
    },
    planIcon: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: 'rgba(255,255,255,0.14)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    planEyebrow: {
        fontSize: 10.5,
        color: 'rgba(255,255,255,0.75)',
        fontFamily: Fonts.PoppinsMedium,
    },
    planName: {
        fontSize: 14,
        color: '#FFFFFF',
        fontFamily: Fonts.PoppinsSemiBold,
    },
    planMeta: {
        marginTop: 1,
        fontSize: 11,
        color: '#E8C27A',
        fontFamily: Fonts.PoppinsSemiBold,
    },
    planActions: {
        alignItems: 'flex-end',
        gap: 6,
    },
    planChangeBtn: {
        backgroundColor: '#E8C27A',
        borderRadius: 999,
        paddingHorizontal: 10,
        paddingVertical: 4,
    },
    planChangeText: {
        fontSize: 11,
        color: '#0A4A3C',
        fontFamily: Fonts.PoppinsSemiBold,
    },
    planRemoveText: {
        fontSize: 11,
        color: 'rgba(255,255,255,0.8)',
        fontFamily: Fonts.PoppinsMedium,
        textDecorationLine: 'underline',
    },
    planPrompt: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        marginHorizontal: 10,
        marginTop: 8,
        borderRadius: 14,
        padding: 12,
        backgroundColor: '#FFF8EB',
        borderWidth: 1,
        borderColor: '#F5D9A3',
    },
    planPromptIcon: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: '#FDE9C4',
        alignItems: 'center',
        justifyContent: 'center',
    },
    planPromptTitle: {
        fontSize: 13,
        color: '#5B3A0A',
        fontFamily: Fonts.PoppinsSemiBold,
    },
    planPromptSub: {
        fontSize: 11,
        color: '#8A5A12',
        fontFamily: Fonts.PoppinsMedium,
    },
    planPromptCta: {
        fontSize: 12,
        color: Colors.primaryColor,
        fontFamily: Fonts.PoppinsSemiBold,
    },
    scrollContent: {
        paddingBottom: 8,
    },

    heroCard: {
        paddingHorizontal: 14,
        paddingTop: 12,
        paddingBottom: 12,
    },
    heroRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    avatarWrap: {
        width: 64,
        height: 64,
        borderRadius: 14,
        overflow: 'hidden',
        backgroundColor: '#F0F7F4',
        borderWidth: 2,
        borderColor: '#A7E0CF',
    },
    avatar: {
        width: '100%',
        height: '100%',
        resizeMode: 'cover',
    },
    avatarFallback: {
        flex: 1,
        backgroundColor: '#DFE5E7',
        alignItems: 'center',
        justifyContent: 'center',
    },
    avatarLetter: {
        fontSize: 24,
        color: '#FFFFFF',
        fontFamily: Fonts.PoppinsBold,
    },
    heroInfo: {
        flex: 1,
        minWidth: 0,
    },
    doctorName: {
        fontSize: 16,
        fontFamily: Fonts.PoppinsSemiBold,
        color: '#0F172A',
        lineHeight: 21,
    },
    qualification: {
        marginTop: 1,
        fontSize: 12,
        fontFamily: Fonts.PoppinsMedium,
        color: '#64748B',
    },
    secureChip: {
        marginTop: 6,
        alignSelf: 'flex-start',
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        backgroundColor: '#ECF8F3',
        paddingHorizontal: 8,
        paddingVertical: 3,
        borderRadius: 6,
    },
    secureChipText: {
        fontSize: 10,
        fontFamily: Fonts.PoppinsSemiBold,
        color: Colors.primaryColor,
        includeFontPadding: false,
    },

    slotStrip: {
        marginTop: 12,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#D7EBE3',
        paddingVertical: 10,
        paddingHorizontal: 10,
    },
    slotItem: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    slotIcon: {
        width: 28,
        height: 28,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
    },
    slotDivider: {
        width: StyleSheet.hairlineWidth,
        height: 28,
        backgroundColor: '#E2E8F0',
        marginHorizontal: 8,
    },
    slotLabel: {
        fontSize: 10,
        fontFamily: Fonts.PoppinsMedium,
        color: '#94A3B8',
        includeFontPadding: false,
    },
    slotValue: {
        fontSize: 12,
        fontFamily: Fonts.PoppinsSemiBold,
        color: '#0F172A',
        includeFontPadding: false,
    },

    card: {
        marginTop: 8,
        marginHorizontal: 10,
        paddingHorizontal: 12,
        paddingTop: 12,
        paddingBottom: 12,
        borderRadius: 14,
        backgroundColor: '#FFFFFF',
        borderWidth: StyleSheet.hairlineWidth,
        borderColor: '#E8EEF2',
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginBottom: 10,
    },
    sectionIcon: {
        width: 28,
        height: 28,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
    },
    sectionTitle: {
        fontSize: 14,
        fontFamily: Fonts.PoppinsSemiBold,
        color: '#0F172A',
        includeFontPadding: false,
    },

    patientRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
    },
    patientAvatar: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#EEF2FF',
        alignItems: 'center',
        justifyContent: 'center',
    },
    patientInitial: {
        fontSize: 15,
        fontFamily: Fonts.PoppinsSemiBold,
        color: '#4F46E5',
    },
    patientName: {
        fontSize: 14,
        fontFamily: Fonts.PoppinsSemiBold,
        color: '#0F172A',
    },
    patientMeta: {
        marginTop: 1,
        fontSize: 11,
        fontFamily: Fonts.PoppinsMedium,
        color: '#64748B',
    },
    changePatientBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 2,
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: Colors.bgborderColor,
        backgroundColor: Colors.onfillColor,
        minWidth: 72,
        justifyContent: 'center',
    },
    changePatientText: {
        fontSize: 11,
        fontFamily: Fonts.PoppinsSemiBold,
        color: Colors.primaryColor,
        includeFontPadding: false,
    },

    pickerOverlay: {
        flex: 1,
        backgroundColor: 'rgba(15, 23, 42, 0.4)',
        justifyContent: 'flex-end',
    },
    pickerSheet: {
        backgroundColor: '#FFFFFF',
        borderTopLeftRadius: 18,
        borderTopRightRadius: 18,
        paddingHorizontal: 14,
        paddingTop: 12,
        paddingBottom: 20,
        maxHeight: '62%',
        zIndex: 1,
    },
    pickerHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 8,
        paddingHorizontal: 2,
    },
    pickerTitle: {
        fontSize: 15,
        fontFamily: Fonts.PoppinsSemiBold,
        color: '#0F172A',
    },
    pickerList: {
        maxHeight: 360,
    },
    pickerRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        paddingVertical: 10,
        paddingHorizontal: 10,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#E8EEF2',
        marginBottom: 8,
        backgroundColor: '#FFFFFF',
    },
    pickerRowSelected: {
        borderColor: Colors.bgborderColor,
        backgroundColor: Colors.onfillColor,
    },
    pickerAvatar: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: '#F1F5F9',
        alignItems: 'center',
        justifyContent: 'center',
    },
    pickerAvatarSelected: {
        backgroundColor: Colors.primaryColor,
    },
    pickerInitial: {
        fontSize: 13,
        fontFamily: Fonts.PoppinsSemiBold,
        color: '#475569',
    },
    pickerInitialSelected: {
        color: '#FFFFFF',
    },
    pickerName: {
        fontSize: 13,
        fontFamily: Fonts.PoppinsSemiBold,
        color: '#0F172A',
    },
    pickerMeta: {
        marginTop: 1,
        fontSize: 11,
        fontFamily: Fonts.PoppinsMedium,
        color: '#64748B',
    },

    concernBox: {
        marginTop: 10,
        padding: 10,
        borderRadius: 10,
        backgroundColor: '#F8FAFC',
        borderWidth: StyleSheet.hairlineWidth,
        borderColor: '#E2E8F0',
    },
    concernLabel: {
        fontSize: 10,
        fontFamily: Fonts.PoppinsSemiBold,
        color: '#94A3B8',
        textTransform: 'uppercase',
        letterSpacing: 0.3,
        marginBottom: 3,
    },
    concernValue: {
        fontSize: 12,
        lineHeight: 18,
        fontFamily: Fonts.PoppinsRegular,
        color: '#334155',
    },

    docsSection: {
        marginTop: 10,
    },
    docsTitle: {
        fontSize: 11,
        fontFamily: Fonts.PoppinsSemiBold,
        color: '#64748B',
        marginBottom: 6,
    },
    docRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        paddingVertical: 8,
        paddingHorizontal: 10,
        marginBottom: 6,
        borderRadius: 10,
        backgroundColor: '#F8FAFC',
        borderWidth: StyleSheet.hairlineWidth,
        borderColor: '#E2E8F0',
    },
    docName: {
        flex: 1,
        fontSize: 12,
        color: '#0F172A',
        fontFamily: Fonts.PoppinsMedium,
    },
    docType: {
        fontSize: 10,
        color: '#64748B',
        fontFamily: Fonts.PoppinsSemiBold,
    },

    summaryRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 8,
        gap: 8,
    },
    summaryLabel: {
        flex: 1,
        fontSize: 12,
        color: '#64748B',
        fontFamily: Fonts.PoppinsMedium,
    },
    summaryValue: {
        fontSize: 13,
        color: '#0F172A',
        fontFamily: Fonts.PoppinsSemiBold,
    },
    summaryDiscountLabel: {
        flex: 1,
        fontSize: 12,
        color: '#15803D',
        fontFamily: Fonts.PoppinsMedium,
    },
    summaryDiscountValue: {
        fontSize: 13,
        color: '#15803D',
        fontFamily: Fonts.PoppinsSemiBold,
    },
    discountRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    totalStrip: {
        marginTop: 6,
        borderRadius: 12,
        paddingHorizontal: 12,
        paddingVertical: 12,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 10,
    },
    totalLabel: {
        fontSize: 12,
        fontFamily: Fonts.PoppinsSemiBold,
        color: '#14532D',
    },
    secureRow: {
        marginTop: 3,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    secureText: {
        fontSize: 10,
        fontFamily: Fonts.PoppinsMedium,
        color: '#3F6212',
    },
    totalAmount: {
        fontSize: 20,
        fontFamily: Fonts.PoppinsBold,
        color: Colors.primaryColor,
        includeFontPadding: false,
    },

    stickyBar: {
        position: 'absolute',
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: '#FFFFFF',
        borderTopWidth: StyleSheet.hairlineWidth,
        borderTopColor: '#E8F2EE',
        paddingTop: 8,
        paddingHorizontal: 12,
        shadowColor: '#0F172A',
        shadowOffset: { width: 0, height: -2 },
        shadowOpacity: 0.06,
        shadowRadius: 8,
        elevation: 8,
    },
    stickyRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
    },
    stickyPriceBox: {
        minWidth: 96,
    },
    stickyPrice: {
        fontSize: 18,
        fontFamily: Fonts.PoppinsBold,
        color: Colors.primaryColor,
        includeFontPadding: false,
    },
    stickyHint: {
        fontSize: 10,
        fontFamily: Fonts.PoppinsMedium,
        color: '#94A3B8',
        includeFontPadding: false,
    },
    primaryBtnWrap: {
        flex: 1,
        borderRadius: 12,
        overflow: 'hidden',
    },
    primaryBtn: {
        minHeight: 50,
        borderRadius: 12,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        paddingHorizontal: 14,
    },
    primaryBtnText: {
        fontSize: 15,
        fontFamily: Fonts.PoppinsSemiBold,
        color: '#FFFFFF',
    },
    cancelLink: {
        marginTop: 6,
        alignItems: 'center',
        paddingVertical: 4,
    },
    cancelLinkText: {
        fontSize: 12,
        fontFamily: Fonts.PoppinsSemiBold,
        color: '#EF4444',
    },

    verificationScreen: {
        flex: 1,
        backgroundColor: '#FFFFFF',
    },
    verificationContent: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 28,
    },
    verificationTitle: {
        marginTop: 20,
        fontSize: 20,
        color: '#0F172A',
        fontFamily: Fonts.PoppinsSemiBold,
    },
    verificationSubtitle: {
        marginTop: 8,
        fontSize: 13,
        color: '#64748B',
        textAlign: 'center',
        lineHeight: 20,
        fontFamily: Fonts.PoppinsRegular,
    },
    verificationInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 22,
        paddingHorizontal: 14,
        paddingVertical: 10,
        borderRadius: 12,
        backgroundColor: '#F5F8F6',
        gap: 8,
    },
    verificationInfoText: {
        color: '#475569',
        fontSize: 12,
        fontFamily: Fonts.PoppinsMedium,
    },
});
