
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import type { CompositeNavigationProp } from '@react-navigation/native';
import type { BottomTabNavigationProp } from '@react-navigation/bottom-tabs';

export type RootStackParamList = {
    Login: undefined;
    Signup: undefined;
    Otp: undefined;
    MentorCheckout: undefined;
    Onboarding: undefined;
    FavDoctors: undefined;
    AppointmentDetails: undefined;
    HomeStack: undefined;
    PatientVideoCallScreen: undefined;
    AddEditAddress: undefined;
    History: undefined;
    LocationPickerScreen: undefined;
    MultipleDoctorSlip: undefined;
    PrescriptionDetail: undefined;
    AuthStack: undefined;
    DoctorSlot: undefined;
    DoctorProfile: undefined;
    AddCalendar: undefined;
    SplashStack: undefined;
    ConsultHistory: undefined;
    DoctorSlipScreen: undefined;
    ExchangeScreen: undefined;
    WelcomeScreen: undefined;
    PrakritiProfile: undefined;
    OtpVerify: undefined;
    EditProfile: undefined;
    WeeklyMeal: WeeklyMeal;
    MedicalReceipt: undefined;
    AllDoctors: undefined;
    CategoryDoctor: undefined;
    Splash: undefined;
    BookingConfrimScreen: undefined;
    Appointments: undefined;
    OrderHistory: undefined;
    TabStack: undefined;
    MentorOrder: undefined;
    PatientDetails: undefined;
    RefundScreen: undefined;
    TermsCondition: undefined;
    YogaScreen: undefined;
    PatientFAQ: undefined;
    AddEditPatientDetail: undefined;
    ConsultMentor: undefined;
    ProductDetails: undefined;
    TopCategories: undefined;
    ReviewPage: undefined;
    YogaSession: undefined;
    MyCart: undefined;
    Mentor: undefined;
    RazorpayScreen: undefined;
    Checkout: undefined;
    DietScreen: undefined;
    Wishlist: undefined;
    MedicalRecords: undefined;
    OrderConfirmation: undefined;
    MedicineScreen: undefined;
    ProductsScreen: undefined;
    FAQScreen: undefined;
    HelpCenterScreen: undefined;
    Settings: undefined;
    PaymentsScreen: undefined;
    EmergencySOS: undefined;
    SOSConfirmed: undefined;
    SOSCancel: undefined;
    SOSPayment: undefined;
    MealDetails: undefined;
    SOSConfirmed: undefined;
    SOSRequest: undefined;
    Notifications: undefined;
    ManageAdrees: undefined;
    Prescription: undefined;
    VerifyPresciption: undefined;
    SearchScreen: undefined;
    OrderStatus: undefined;
    MedicineCheckOut: undefined;
    consultHome: undefined;
    MedicalHistory: undefined;
    AssessmentType: undefined;
};


export type RootBottomParamList = {
    Home: undefined;
    Shop: undefined;
    Centers: undefined;
    Medicine: undefined;
    History: undefined;
    Diet: undefined;
    MyCart: undefined;
    Products: undefined;
    Profile: undefined;
    Consult: undefined;
    consultHome: undefined;
    Mentor: undefined;
};

export type AllBooksScreenProps = NativeStackScreenProps<RootStackParamList, 'AllBooks'>

