import { StyleSheet } from 'react-native';
import { Fonts } from '../../common/Fonts';
import { Colors } from '../../common/Colors';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F4F7F6',
    },

    skeletonWrap: {
        flex: 1,
    },

    scrollView: {
        flex: 1,
        paddingHorizontal: 12,
    },

    scrollContent: {
        flexGrow: 1,
        paddingTop: 4,
    },

    tabContainer: {
        marginTop: 6,
        marginBottom: 12,
    },

    tabsAlwaysWrap: {
        paddingHorizontal: 12,
        paddingTop: 4,
        backgroundColor: Colors.background,
    },

    outOfStockBanner: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        backgroundColor: '#DC2626',
        borderRadius: 10,
        paddingHorizontal: 12,
        paddingVertical: 11,
        marginBottom: 10,
    },
    outOfStockBannerIcon: {
        width: 28,
        height: 28,
        borderRadius: 14,
        backgroundColor: 'rgba(255,255,255,0.2)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    outOfStockBannerTextWrap: {
        flex: 1,
        minWidth: 0,
    },
    outOfStockBannerTitle: {
        fontSize: 13,
        color: '#FFFFFF',
        fontFamily: Fonts.PoppinsSemiBold,
        marginBottom: 1,
    },
    outOfStockBannerSub: {
        fontSize: 11,
        lineHeight: 15,
        color: 'rgba(255,255,255,0.88)',
        fontFamily: Fonts.PoppinsRegular,
    },

    oosPanel: {
        backgroundColor: '#FEF2F2',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#FECACA',
        paddingHorizontal: 14,
        paddingTop: 12,
        paddingBottom: 8,
        marginBottom: 10,
    },
    oosPanelHeader: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: 10,
        marginBottom: 10,
    },
    oosPanelIcon: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: '#DC2626',
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 1,
    },
    oosPanelTitle: {
        fontSize: 14,
        lineHeight: 20,
        color: '#B91C1C',
        fontFamily: Fonts.PoppinsSemiBold,
    },
    oosPanelSub: {
        marginTop: 2,
        fontSize: 11,
        lineHeight: 15,
        color: '#7F1D1D',
        fontFamily: Fonts.PoppinsRegular,
    },
    oosItemRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        // paddingVertical: 0,
        borderTopWidth: StyleSheet.hairlineWidth,
        borderTopColor: '#F1F5F9',
    },
    oosThumb: {
        width: 44,
        height: 44,
        borderRadius: 8,
        backgroundColor: '#F8FAFC',
    },
    oosThumbFallback: {
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: '#E2E8F0',
    },
    oosItemCopy: {
        flex: 1,
        minWidth: 0,
    },
    oosItemName: {
        fontSize: 13,
        lineHeight: 18,
        color: '#0F172A',
        fontFamily: Fonts.PoppinsMedium,
    },
    oosItemHint: {
        marginTop: 2,
        fontSize: 11,
        color: '#B91C1C',
        fontFamily: Fonts.PoppinsMedium,
    },
    oosRemoveBtn: {
        width: 32,
        height: 32,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#FEF2F2',
    },
    tabEmptyWrap: {
        paddingVertical: 28,
        alignItems: 'center',
    },
    tabEmptyText: {
        fontSize: 13,
        color: '#94A3B8',
        fontFamily: Fonts.PoppinsMedium,
    },

    trustStrip: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 10,
        paddingHorizontal: 6,
        marginBottom: 10,
    },
    trustItem: {
        flex: 1,
        alignItems: 'center',
        gap: 4,
    },
    trustIcon: {
        width: 28,
        height: 28,
        borderRadius: 14,
        alignItems: 'center',
        justifyContent: 'center',
    },
    trustText: {
        fontSize: 10,
        color: '#334155',
        fontFamily: Fonts.PoppinsMedium,
        textAlign: 'center',
    },
    trustDivider: {
        width: StyleSheet.hairlineWidth,
        height: 28,
        backgroundColor: '#E2E8F0',
    },

    selectAllRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 8,
        paddingHorizontal: 2,
    },
    selectAllText: {
        fontSize: 12,
        color: '#64748B',
        fontFamily: Fonts.PoppinsMedium,
    },

    checkbox: {
        width: 22,
        height: 22,
        borderRadius: 7,
        borderWidth: 1.5,
        borderColor: '#CAD5D1',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#FFF',
    },
    lineCheck: {
        width: 18,
        height: 18,
        borderRadius: 5,
        borderWidth: 1.5,
        borderColor: '#CAD5D1',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#FFF',
    },
    lineCheckDisabled: {
        backgroundColor: '#F1F5F9',
        borderColor: '#E2E8F0',
    },
    thumbCheck: {
        position: 'absolute',
        right: -3,
        bottom: -3,
        width: 14,
        height: 14,
        borderRadius: 4,
        borderWidth: 1,
        borderColor: '#CAD5D1',
        backgroundColor: '#FFFFFF',
        alignItems: 'center',
        justifyContent: 'center',
    },
    checkboxActive: {
        backgroundColor: Colors.primaryColor,
        borderColor: Colors.primaryColor,
    },

    viewMoreBtn: {
        marginTop: 4,
        marginBottom: 12,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 4,
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#D7E8E3',
        paddingVertical: 12,
    },
    viewMoreText: {
        fontSize: 13,
        color: Colors.primaryColor,
        fontFamily: Fonts.PoppinsSemiBold,
    },
    doctorCard: {
        backgroundColor: '#F7FBFA',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#B7D9D0',
        paddingHorizontal: 10,
        paddingVertical: 8,
        marginBottom: 8,
    },
    doctorKicker: {
        fontSize: 10,
        color: Colors.primaryColor,
        fontFamily: Fonts.PoppinsSemiBold,
    },
    doctorSymptom: {
        marginTop: 6,
        fontSize: 11,
        color: '#64748B',
        fontFamily: Fonts.PoppinsRegular,
    },
    uploadCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#D7E8E3',
        paddingHorizontal: 10,
        paddingVertical: 8,
        marginBottom: 8,
    },
    uploadTop: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    uploadTitle: {
        fontSize: 13,
        color: '#0F172A',
        fontFamily: Fonts.PoppinsSemiBold,
    },
    uploadMeta: {
        marginTop: 1,
        fontSize: 11,
        color: '#64748B',
        fontFamily: Fonts.PoppinsRegular,
    },
    uploadStatus: {
        borderRadius: 999,
        paddingHorizontal: 7,
        paddingVertical: 3,
    },
    uploadStatusText: {
        fontSize: 10,
        fontFamily: Fonts.PoppinsSemiBold,
    },
    uploadThumbRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        marginTop: 8,
    },
    uploadThumbWrap: {
        width: 36,
        height: 36,
    },
    uploadThumb: {
        width: 36,
        height: 36,
        borderRadius: 8,
        backgroundColor: '#F1F5F9',
    },
    uploadThumbFallback: {
        alignItems: 'center',
        justifyContent: 'center',
    },
    uploadMore: {
        position: 'absolute',
        top: 0,
        right: 0,
        bottom: 0,
        left: 0,
        borderRadius: 8,
        backgroundColor: 'rgba(15, 23, 42, 0.45)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    uploadMoreText: {
        color: '#FFFFFF',
        fontSize: 11,
        fontFamily: Fonts.PoppinsSemiBold,
    },
    uploadItemList: {
        marginTop: 6,
        gap: 6,
    },
    uploadItemRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    uploadItemTap: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        minWidth: 0,
    },
    uploadItemName: {
        fontSize: 12,
        color: '#0F172A',
        fontFamily: Fonts.PoppinsMedium,
    },
    uploadItemMeta: {
        fontSize: 10,
        color: '#64748B',
        fontFamily: Fonts.PoppinsRegular,
    },
    uploadItemPrice: {
        fontSize: 12,
        color: '#0F172A',
        fontFamily: Fonts.PoppinsSemiBold,
    },
    uploadActions: {
        marginTop: 6,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    uploadCollapse: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 2,
    },
    uploadCollapseText: {
        fontSize: 12,
        color: '#475569',
        fontFamily: Fonts.PoppinsSemiBold,
    },
    uploadDetails: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 2,
    },
    uploadDetailsText: {
        fontSize: 12,
        color: Colors.primaryColor,
        fontFamily: Fonts.PoppinsSemiBold,
    },
    productsWrap: {
        marginBottom: 8,
    },

    emptyContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 32,
    },
    emptyIconCircle: {
        width: 88,
        height: 88,
        borderRadius: 44,
        backgroundColor: '#EAF8F4',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 16,
    },
    emptyTitle: {
        fontSize: 18,
        fontFamily: Fonts.PoppinsSemiBold,
        color: '#0F172A',
        textAlign: 'center',
    },
    emptySubTitle: {
        fontSize: 13,
        color: '#64748B',
        textAlign: 'center',
        marginTop: 6,
        lineHeight: 18,
        fontFamily: Fonts.PoppinsRegular,
    },
    shopNowBtn: {
        marginTop: 20,
        backgroundColor: Colors.primaryColor,
        paddingHorizontal: 28,
        paddingVertical: 12,
        borderRadius: 12,
    },
    shopNowText: {
        color: '#FFF',
        fontSize: 14,
        fontFamily: Fonts.PoppinsSemiBold,
    },

    orderHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 10,
    },
    orderTitle: {
        fontSize: 13,
        color: '#0F172A',
        fontFamily: Fonts.PoppinsSemiBold,
    },
    viewDetails: {
        fontSize: 12,
        color: Colors.primaryColor,
        fontFamily: Fonts.PoppinsSemiBold,
    },

    billBox: {
        backgroundColor: '#FFF',
        borderRadius: 14,
        padding: 14,
        marginBottom: 8,
    },
    billRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 8,
    },
    billRowTotal: {
        marginBottom: 0,
        marginTop: 2,
        paddingTop: 8,
        borderTopWidth: StyleSheet.hairlineWidth,
        borderTopColor: '#E2E8F0',
    },
    billLabel: {
        fontSize: 13,
        color: '#64748B',
        fontFamily: Fonts.PoppinsMedium,
    },
    billLabelTotal: {
        fontSize: 14,
        color: '#0F172A',
        fontFamily: Fonts.PoppinsSemiBold,
    },
    billValue: {
        fontSize: 13,
        color: '#0F172A',
        fontFamily: Fonts.PoppinsSemiBold,
    },
    billValueTotal: {
        fontSize: 16,
        color: Colors.primaryColor,
    },
    billValueSuccess: {
        color: '#15803D',
    },
    feeNote: {
        marginTop: -4,
        marginBottom: 8,
        fontSize: 11,
        lineHeight: 15,
        color: '#15803D',
        fontFamily: Fonts.PoppinsMedium,
    },
    feeNoteMuted: {
        marginTop: -4,
        marginBottom: 8,
        fontSize: 11,
        lineHeight: 15,
        color: '#94A3B8',
        fontFamily: Fonts.PoppinsMedium,
    },
    divider: {
        height: StyleSheet.hairlineWidth,
        backgroundColor: '#E2E8F0',
        marginVertical: 6,
    },

    checkoutFooter: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        paddingTop: 10,
        paddingHorizontal: 12,
        backgroundColor: '#FFFFFF',
        borderTopWidth: StyleSheet.hairlineWidth,
        borderTopColor: '#E2E8F0',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -2 },
        shadowOpacity: 0.06,
        shadowRadius: 6,
        elevation: 10,
    },
    footerPriceBox: {
        minWidth: 72,
        flexShrink: 0,
    },
    footerTotal: {
        fontSize: 16,
        color: '#0F172A',
        fontFamily: Fonts.PoppinsSemiBold,
        includeFontPadding: false,
    },
    footerHint: {
        marginTop: 1,
        fontSize: 11,
        color: '#64748B',
        fontFamily: Fonts.PoppinsMedium,
        includeFontPadding: false,
    },
    checkoutBtnWrap: {
        flex: 1,
        borderRadius: 12,
        overflow: 'hidden',
    },
    checkoutBtnDisabled: {
        opacity: 0.55,
    },
    checkoutBtn: {
        height: 48,
        borderRadius: 12,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 4,
        paddingHorizontal: 16,
    },
    checkoutText: {
        fontSize: 15,
        color: '#FFF',
        fontFamily: Fonts.PoppinsSemiBold,
    },
});
