
auth.token=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

defaults.org=aimantra
defaults.project=react-native

defaults.url=https://sentry.io/
