import React from 'react';
import { View } from 'react-native';
import {
  IconShoppingCart,
  IconBell,
  IconChevronDown,
  IconChevronRight,
  IconChevronLeft,
  IconChevronUp,
  IconHome,
  IconPackage,
  IconPill,
  IconUser,
  IconStethoscope,
  IconPlus,
  IconMinus,
  IconStar,
  IconStarFilled,
  IconHeart,
  IconHeartFilled,
  IconSearch,
  IconMapPin,
  IconCrosshair,
  IconArrowLeft,
  IconArrowRight,
  IconEdit,
  IconX,
  IconCheck,
  IconTrash,
  IconFilter,
  IconShare,
  IconClock,
  IconCalendar,
  IconPhone,
  IconMessage,
  IconLocation,
  IconBriefcase,
  IconUsers,
  IconClipboardList,
  IconReceipt,
  IconStethoscope as IconFileMedical,
  IconSchool,
  IconChartPie,
  IconCreditCard,
  IconSettings,
  IconHelp,
  IconLogout,
  IconBuildingStore,
  IconTruck,
  IconPhoto,
  IconVideo,
  IconUpload,
  IconDownload,
  IconEye,
  IconLock,
  IconMail,
  IconAlertCircle,
  IconBuilding,
  IconCash,
  IconBolt,
  IconCamera,
  IconFile,
  IconCircleCheck,
  IconReport,
  IconNotes,
  IconListDetails,
  IconRefresh,
  IconArrowsExchange,
  IconCurrentLocation,
  IconBrandWhatsapp,
  IconMicrophone,
  IconCertificate,
  IconShieldCheck,
  IconWallet,
  IconHistory,
  IconMoodSmile,
  IconMoodSad,
} from '@tabler/icons-react-native';
import { Colors } from '../common/Colors';

const ICON_MAP = {
  'shopping-cart': IconShoppingCart,
  bell: IconBell,
  'chevron-down': IconChevronDown,
  'chevron-right': IconChevronRight,
  'chevron-left': IconChevronLeft,
  'chevron-up': IconChevronUp,
  home: IconHome,
  package: IconPackage,
  pill: IconPill,
  user: IconUser,
  users: IconUsers,
  stethoscope: IconStethoscope,
  plus: IconPlus,
  minus: IconMinus,
  star: IconStar,
  'star-filled': IconStarFilled,
  heart: IconHeart,
  'heart-filled': IconHeartFilled,
  search: IconSearch,
  'map-pin': IconMapPin,
  crosshair: IconCrosshair,
  'arrow-left': IconArrowLeft,
  'arrow-right': IconArrowRight,
  edit: IconEdit,
  x: IconX,
  check: IconCheck,
  trash: IconTrash,
  filter: IconFilter,
  share: IconShare,
  clock: IconClock,
  calendar: IconCalendar,
  phone: IconPhone,
  message: IconMessage,
  location: IconLocation,
  briefcase: IconBriefcase,
  'clipboard-list': IconClipboardList,
  receipt: IconReceipt,
  'file-medical': IconFileMedical,
  school: IconSchool,
  'chart-pie': IconChartPie,
  'credit-card': IconCreditCard,
  settings: IconSettings,
  help: IconHelp,
  logout: IconLogout,
  store: IconBuildingStore,
  truck: IconTruck,
  photo: IconPhoto,
  video: IconVideo,
  upload: IconUpload,
  download: IconDownload,
  eye: IconEye,
  lock: IconLock,
  mail: IconMail,
  'alert-circle': IconAlertCircle,
  building: IconBuilding,
  cash: IconCash,
  bolt: IconBolt,
  camera: IconCamera,
  file: IconFile,
  'circle-check': IconCircleCheck,
  report: IconReport,
  notes: IconNotes,
  list: IconListDetails,
  refresh: IconRefresh,
  exchange: IconArrowsExchange,
  'current-location': IconCurrentLocation,
  whatsapp: IconBrandWhatsapp,
  mic: IconMicrophone,
  certificate: IconCertificate,
  shield: IconShieldCheck,
  wallet: IconWallet,
  history: IconHistory,
  'mood-smile': IconMoodSmile,
  'mood-sad': IconMoodSad,
  approved: IconCircleCheck,
  verify: IconCircleCheck,
  unverify: IconAlertCircle,
  notification: IconBell,
  consult: IconStethoscope,
  'chat-support': IconMessage,
  prescription: IconFileMedical,
  ingredient: IconListDetails,
  refund: IconRefresh,
  favourite: IconHeart,
  wishlist: IconHeart,
  orders: IconReceipt,
  payment: IconCreditCard,
  patient: IconUsers,
  medical: IconFileMedical,
  cart: IconShoppingCart,
  upi: IconWallet,
  card: IconCreditCard,
  flash: IconBolt,
  dropdown: IconChevronDown,
  tick: IconCheck,
  'tick-icon': IconCircleCheck,
  spoon: IconListDetails,
  breakdown: IconListDetails,
  instruction: IconNotes,
  'plus-bag': IconShoppingCart,
  medicines: IconPill,
  office: IconBuilding,
  sos: IconAlertCircle,
} as const;

export type TablerIconName = keyof typeof ICON_MAP;

type Props = {
  name: TablerIconName;
  size?: number;
  color?: string;
  strokeWidth?: number;
  style?: object;
};

const TablerIcon: React.FC<Props> = ({
  name,
  size = 22,
  color = Colors.primaryColor,
  strokeWidth = 2,
  style,
}) => {
  const IconComponent = ICON_MAP[name];
  if (!IconComponent) return null;
  return (
    <View style={style}>
      <IconComponent size={size} color={color} strokeWidth={strokeWidth} />
    </View>
  );
};

export default TablerIcon;
