
export const Images = {
    backIcon: require('../assets/images/backButton.png'),
    FinalLogo: require('../assets/images/FinalLogo.png'),
    FinalLogo2: require('../assets/images/FinalLogo2.png'),
    login1: require('../assets/images/login/1.png'),
    login3: require('../assets/images/login/3.png'),
    login4: require('../assets/images/login/4.png'),
    login5: require('../assets/images/login/5.png'),
    login2: require('../assets/images/login/2.png'),

    login6: require('../assets/images/login/6.jpg'),
    login7: require('../assets/images/login/7.jpg'),
    login8: require('../assets/images/login/8.png'),
    login9: require('../assets/images/login/9.png'),
    login10: require('../assets/images/login/10.png'),
    login11: require('../assets/images/login/11.png'),
    login12: require('../assets/images/login/12.png'),
    login13: require('../assets/images/login/13.png'),
    login14: require('../assets/images/login/14.jpg'),


    ayurvedic: require('../assets/images/login/ayurvedic.jpeg'),
    dietlifestyle: require('../assets/images/login/dietlifestyle.jpeg'),
    delivery: require('../assets/images/login/delivery.png'),
    lab: require('../assets/images/login/lab.png'),
    online: require('../assets/images/login/10.png'),
    journeyConsult: require('../assets/images/login/10.png'),
    journeyMedicine: require('../assets/images/login/9.png'),
    journeyDelivery: require('../assets/images/login/delivery.png'),
    journeyLab: require('../assets/images/login/ayurvedic.jpeg'),
    journeyDiet: require('../assets/images/login/14.jpg'),
    journeyYoga: require('../assets/images/login/8.png'),

    HomeBanner: require('../assets/images/banner.png'),
    BackgroundImage: require('../assets/images/BGImage.png'),
    doctorImage: require('../assets/images/doctorImage.png'),
    FAQImage: require('../assets/images/FAQImage.png'),
    networkissue: require('../assets/images/networklogo.png'),
    yesHuman: require('../assets/images/Yes.png'),
    noHuman: require('../assets/images/No.png'),
    doc1: require('../assets/images/doc1.png'),

    cardiology: require('../assets/images/cardiology.png'),
    leaf1: require('../assets/images/leaf1.png'),
    leaf2: require('../assets/images/leaf2.png'),
    Panchakarma: require('../assets/images/panchkarma.png'),
    profileEdit: require('../assets/images/profileEdit.png'),
    RecentsImage: require('../assets/images/RecentsImage.png'),
    Ingredient: require('../assets/images/Ingredient.png'),
    HelloIcon: require('../assets/images/HelloIcon.png'),
    doctorbanner: require('../assets/images/doctorbanner.png'),
};

export const Icons = {};
