export const Images = {
    backIcon:require('../assets/images/BackButoon.png'),
    newlogo:require('../assets/images/MainIcon.png'),
    MobileLogo:require('../assets/images/MobileLogo.png'),
    splashlogo: require('../assets/images/logo.png'),
    networkissue: require('../assets/images/networklogo.png'),
    ellipsebackground: require('../assets/images/Ellipse.png'),
    userprofile: require('../assets/images/userprofile.png'),
    robotIcon: require('../assets/images/friendly-robot.png'),
    askbutton: require('../assets/images/AskButton.png'),
    organicIcon: require('../assets/images/organicIcon.png'),
    medicines: require('../assets/images/medicines.png'),
    consultant: require('../assets/images/consultant.png'),
    askmuniIcon: require('../assets/images/askMuniIcon.png'),
    wellness: require('../assets/images/wellnessIcon.png'),
    detailimage: require('../assets/images/Detailimage.png'),
    share: require('../assets/images/Share.png'),
    searchIcon: require('../assets/images/search.png'),
    micIcon: require('../assets/images/Mic.png'),
    linemark: require('../assets/images/Linemark.png'),
    takechnageIcons: require('../assets/images/TakechangeIcon.png'),
    centers: require('../assets/images/centers.png'),
    profile: require('../assets/images/profile.png'),
    consult: require('../assets/images/consult.png'),
    shop: require('../assets/images/shop.png'),
    home: require('../assets/images/home.png'),
    loginbanner: require('../assets/images/loginbanner.png'),
    homebanner: require('../assets/images/Homebanner.png'),
    mobilelogo: require('../assets/images/MobileLogo.png'),
    verifylogo: require('../assets/images/verifyLogo.png'),
    messageIcon: require('../assets/images/messageIcon.png'),
    prescription: require('../assets/images/prescription.png'),
    backgroundFlower: require('../assets/images/backgroundFlower.png'),
    meditationIcon: require('../assets/images/meditationIcon.png'),
    googleIcon: require('../assets/images/googleIcon.png'),
    phoneIcon: require('../assets/images/phoneIcon.png'),
    frame1: require('../assets/images/Frame1.png'),
    spinner: require('../assets/images/Spinner-Gradient.png'),
    star: require('../assets/images/grade.png'),
    nutritionIcon: require('../assets/images/nutritionIcon.png'),
    deleteitem: require('../assets/images/DeleteItem.png'),

    
    
}

export const Icons = {
}


export const QUESTION_IMAGES = {
    knowPrakriti: require('../assets/images/Prakriti.png'),
    prakriti: require('../assets/images/Prakriti2.png'),
    bodyType: require('../assets/images/Body.png'),
    scalpHair: require('../assets/images/SPrakriti.png'),
    bodyHair: require('../assets/images/BodyHair.png'),
    skin: require('../assets/images/Skin.png'),
    appetite: require('../assets/images/Appetite.png'),
    bowel: require('../assets/images/Bowel.png'),
    sweating: require('../assets/images/Sweating.png'),
    sleep: require('../assets/images/Sleep.png'),
    learning: require('../assets/images/Potential.png'),
    temperament: require('../assets/images/Temp.png'),
    personality: require('../assets/images/persnal2.png'),
};
